# HTML
# Archive your static HTML project and save it with the build record.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: default

variables:
  sshVMDetails: "htmlVM"
  registryServiceConnection: "docker-sevice"
  url: "devopstestsukhil.azurecr.io"
  imagename: "sample"

steps:
  - task: Docker@2
    inputs:
      containerRegistry: '$(registryServiceConnection)'
      repository: '$(imagename)'
      command: buildAndPush
      Dockerfile: "./Dockerfile"
      tags: '$(Build.BuildId)'
# - task: SSH@0
#   inputs:
#     sshEndpoint: $(sshVMDetails)
#     runOptions: commands
#     commands: |
#       echo "hi everyone" > index.html
#       sudo cp index.html /var/www/html/index.html
#       sudo systemctl restart nginx
    

    
